Smart/Controllers/KPIController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Smart.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Extensions.Internal;
using System;

namespace Smart.Controllers
{
    public class KPIController : Controller
    {
        private readonly Smart_DBContext _context;

        public KPIController(Smart_DBContext context)
        {

            _context = context;
        }

        public void listSales()
        {
            string level = HttpContext.Session.GetString("userLevel");
            List<SelectListItem> selection = new List<SelectListItem>();
            selection.Add(new SelectListItem { Text = "--- Select Region ---", Value = "0" });
            if (level == "Regional" || level == "Country")
            {
                selection.Add(new SelectListItem { Text = "Country", Value = "country" });
                selection.Add(new SelectListItem { Text = "Channel", Value = "channel" });
                selection.Add(new SelectListItem { Text = "Cluster", Value = "cluster" });
                selection.Add(new SelectListItem { Text = "Region", Value = "region" });
                selection.Add(new SelectListItem { Text = "Territory", Value = "territory" });
            }
            else if (level == "Channel")
            {
                selection.Add(new SelectListItem { Text = "Channel", Value = "channel" });
                selection.Add(new SelectListItem { Text = "Cluster", Value = "cluster" });
                selection.Add(new SelectListItem { Text = "Region", Value = "region" });
                selection.Add(new SelectListItem { Text = "Territory", Value = "territory" });
            }
            else if (level == "Cluster")
            {
                selection.Add(new SelectListItem { Text = "Cluster", Value = "cluster" });
                selection.Add(new SelectListItem { Text = "Region", Value = "region" });
                selection.Add(new SelectListItem { Text = "Territory", Value = "territory" });
            }
            else if (level == "Region")
            {
                selection.Add(new SelectListItem { Text = "Region", Value = "region" });
                selection.Add(new SelectListItem { Text = "Territory", Value = "territory" });
            }
            else
            {
                selection.Add(new SelectListItem { Text = "Territory", Value = "territory" });
            }
            ViewData["regional"] = selection;

            int month_min = System.Convert.ToInt32(_context.DashboardSellThruSummary.Min(x => x.Month));
            int month_max = System.Convert.ToInt32(_context.DashboardSellThruSummary.Max(x => x.Month));
            List<SelectListItem> monthSelect = new List<SelectListItem>();
            monthSelect.Add(new SelectListItem { Text = "--- Select Month ---", Value = "0" });
            for (int i = month_min; i <= month_max; i++)
            {
                monthSelect.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            }

            ViewData["month"] = monthSelect;
        }

        [HttpGet]
        public IActionResult Index()
        {
            listSales();
            return View();
        }

        [HttpPost]
        public ActionResult Index(KPIModelView model)
        {
            listSales();

            string pick = HttpContext.Request.Form["pick"];
            string select = HttpContext.Request.Form["select"];
            string area = HttpContext.Request.Form["area"];
            string areaSelect = HttpContext.Request.Form["areaSelect"];
            string month = HttpContext.Request.Form["month"];

            model.pick = pick;
            model.select = select;
            model.area = area;
            model.areaSelect = area;
            model.month = month;

            var effReach = new KPIModelView();
            effReach.EffReachLists = new List<EffReachLists>();

            string id;
            string areaId;
            double monthId;
            if (pick != null)
            {
                id = select;
                areaId = area;
                monthId = System.Convert.ToDouble(month);
                ViewBag.Message = id + " "+ areaId+ " "+monthId;

                double effReachAct;
                double effReachTarget;
                double effReachPercentage;
                double _effReachMax; double effReachMax = 0;
                string effReachGap;
                string styleEffReach;

                var effReachList = new List<string>();
                var effReachListItem = new List<string>();
                effReachList = _context.Hirarki.Where(w => w.RegionName.Contains(areaSelect)).GroupBy(x => x.DistributorId).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
                foreach (var item in effReachList)
                {
                    effReachListItem = _context.EffReachDetail.Where(w => w.DistributorId == item).GroupBy(x => x.Category).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
                    _effReachMax = System.Math.Round(_context.EffReachDetail.Where(x => x.Month == monthId && x.DistributorId.Contains(item) && x.Tipe != "Act").Select(y => y.Amount ?? 0).Sum(), 2);
                    effReachMax += _effReachMax;
                }
                foreach (var items in effReachListItem)
                {
                    effReachAct = System.Math.Round(_context.EffReachDetail.Where(x => x.Month == monthId && x.Category.Contains(items) && x.Tipe != "Act").Select(y => y.Amount ?? 0).Sum(), 2);
                    effReachTarget = System.Math.Round(_context.EffReachDetail.Where(x => x.Month == monthId && x.Category.Contains(items) && x.Tipe != "Target").Select(y => y.Amount ?? 0).Sum(), 2);
                    effReachPercentage = effReachAct - effReachTarget;
                    if (effReachPercentage > 0)
                    {
                        styleEffReach = "green";
                        effReachGap = "Over :" + effReachPercentage;
                    }
                    else
                    {
                        styleEffReach = "red";
                        effReachGap = "Gap :" + effReachPercentage;
                    }
                    effReach.EffReachLists.Add(new EffReachLists
                    {
                        nameEffReach = items,
                        effReachAct = effReachAct,
                        effReachTarget = effReachTarget,
                        effReachPercentage = effReachPercentage,
                        effReachGap = effReachGap,
                        styleEffReach = styleEffReach
                    });
                }
                ViewData["effReachMax"] = effReachMax;
            }
            else
            {
                id = model.selectionId;
                areaId = model.areaId;
                monthId = System.Convert.ToDouble(model.monthId);
            }
            
            var summaries = new KPIModelView();
            summaries.KPIList = new List<KPILists>();

            double sumSummarySellThru; double percentageSummarySellThru;
            double targetSummarySellThru; double topWidthSellThru;
            double topSummarySellThru; double nonTopWidthSellThru;
            double nonTopSummarySellThru; double nonTopPercentageSellThru;
            double topPercentageSellThru; string summaryGapSellThru;
            string barSellThru, topSellThru, nonSellThru;

            var summaryList = new List<string>();
            double sellTrhuTarget;
            double sellTrhu = 0;

            if (id == "country")
            {
                sellTrhuTarget = _context.Target.Where(x => x.Month == monthId && x.Country.Contains(areaId) && x.Type == "SellThru").Select(y => y.Target1 ?? 0).Sum();
                summaryList = _context.Hirarki.Where(w => w.CountryName.Contains(areaId)).GroupBy(x => x.RegionName).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();

            }
            else if (id == "channel")
            {
                sellTrhuTarget = _context.Target.Where(x => x.Month == monthId && x.Channel.Contains(areaId) && x.Type == "SellThru").Select(y => y.Target1 ?? 0).Sum();
                summaryList = _context.Hirarki.Where(w => w.ChannelName.Contains(areaId)).GroupBy(x => x.RegionName).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
            }
            else if (id == "cluster")
            {
                sellTrhuTarget = _context.Target.Where(x => x.Month == monthId && x.Group.Contains(areaId) && x.Type == "SellThru").Select(y => y.Target1 ?? 0).Sum();
                summaryList = _context.Hirarki.Where(w => w.GroupName.Contains(areaId)).GroupBy(x => x.RegionName).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
            }
            else if (id == "region")
            {
                sellTrhuTarget = _context.Target.Where(x => x.Month == monthId && x.Region.Contains(areaId) && x.Type == "SellThru").Select(y => y.Target1 ?? 0).Sum();
                summaryList = _context.Hirarki.Where(w => w.RegionName.Contains(areaId)).GroupBy(x => x.RegionName).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
            }
            else if (id == "territory")
            {
                sellTrhuTarget = _context.Target.Where(x => x.Month == monthId && x.DistributorId.Contains(areaId) && x.Type == "SellThru").Select(y => y.Target1 ?? 0).Sum();
                summaryList = _context.Hirarki.Where(w => w.DistributorId.Contains(areaId)).GroupBy(x => x.RegionName).Where(y => y.Count() >= 1).Select(z => z.Key).ToList();
            }
            else
            {
                sellTrhuTarget = 0;
                summaryList = null;
            }

Smart/Views/Shared/_KPIPartial.cshtml
<!-- Graphic Effective Reach and DSP -->
<p>@ViewBag.Message</p>
<section id="effectivedsp" class="col-lg-12">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
        <div class="col-lg-12 col-sm-12">
            <h2 style="text-align:center">Effective Reach</h2>
            <!-- GRAPHIC -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Effective Reach Graphic</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                @if (ViewData["selected"] != null)
                {
                    <div class="box-body row">
                        <div class="col-lg-12">
                            <div class="col-lg-3 col-sm-12 col-xs-12">
                                <strong style="color: {{$color}}">{{$effreach[$i]["name"]}}</strong>
                            </div>
                            <div class="col-lg-9 col-sm-12 col-xs-12">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-{{$bar}}" role="progressbar" aria-valuenow="{{$effreach[$i]["act"]}}" aria-valuemin="0" aria-valuemax="{{$maxEffReach}}" style="width:{{100*$effreach[$i]["act"]/$maxEffReach}}%">
                                        {{$effreach[$i]["act"]}}
                                    </div>
                                    {{$effreach[$i]["gap"]}}
                                </div>
                            </div>
                        </div>
                    </div>
                        <!-- /.box-body -->
                }
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
        <div class="col-lg-12 col-sm-12">
            <h2 style="text-align:center">DSP Effectiveness</h2>
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">DSP Effectivity Graphic</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                @if (ViewData["selected"] != null)
                {
                    <div class="box-body row">
                        <div class="col-lg-12">
                            <div class="col-lg-3 col-sm-12 col-xs-12">
                                <strong style="color: {{$color}}">{{$dsp[$i]["name"]}}</strong>
                            </div>
                            <div class="col-lg-9 col-sm-12 col-xs-12">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="{{$dsp[$i]["act"]}}" aria-valuemin="0" aria-valuemax="{{$dsp[$i]["target"]}}" style="width:{{100*$dsp[$i]["act"]/$dsp[$i]["target"]}}%">
                                        {{$dsp[$i]["act"]}}
                                    </div>
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="{{$dsp[$i]["act"]}}" aria-valuemin="0" aria-valuemax="{{$dsp[$i]["target"]}}" style="width:{{100-(100*$dsp[$i]["act"]/$dsp[$i]["target"])}}%">
                                        {{$dsp[$i]["gap"]}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        <!-- /.box-body -->
                }
            </div>
        </div>
    </div>
</section>

Smart/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="public/img/philips-icon.png" rel="icon" type="image/png" />

    <title>Smart - Philips Indonesia</title>
    <!-- Tell the browser to be responsive to screens width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="~/adminlte/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/adminlte/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
            folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/adminlte/plugins/iCheck/flat/blue.css">
    <!-- Morris chart -->
    <link rel="stylesheet" href="~/adminlte/plugins/morris/morris.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="~/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    <!-- Date Picker -->
    <link rel="stylesheet" href="~/adminlte/plugins/datepicker/datepicker3.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="~/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
            folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/adminlte/dist/css/skins/_all-skins.min.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @RenderSection("Styles", required: false)
</head>
<body class="hold-transition skin-blue layout-top-nav">
    <div>
        <header class="main-header">
            <nav class="navbar navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Smart</a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Index</a></li>
                            <li><a asp-area="" asp-controller="SalesAndStock" asp-action="Index">Sales and Stock</a></li>
                            <li><a asp-area="" asp-controller="KPI" asp-action="Index">Process KPI</a></li>
                            <li><a asp-area="" asp-controller="Marketing" asp-action="Index">Marketing Promo Report</a></li>
                            <li><a asp-area="" asp-controller="ARMonitoring" asp-action="Index">AR Monitoring</a></li>
                        </ul>
                    </div>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </div>
    <div class="content-wrapper">
        <div>
            @{string name = HttpContextAccessor.HttpContext.Session.GetString("userName");}
            <div class="content-header col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1><b>SMART</b> <small>Welcome, @name</small></h1>
            </div>
            <div class="content-header col-lg-12 col-md-12 col-sm-12 col-xs-12">
                @RenderSection("PageHeader", required: false)
            </div>
            <div class="content-header col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="background:black"></div>
                <br>
            </div>
            @RenderBody()
        </div>
        <hr />
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>Copyright &copy; 2017 <a href="#">Developer Team</a>.</strong> All rights reserved.
            </div>
            <!-- /.container -->
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js"></script>

    <script>
        $(document).ready(function () {
            $('li.active').removeClass('active');
            $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>

</html>

Smart/Views/Shared/_SalesAndStockPartial.cshtml
<!-- Graphic Sell Thru and Effective Reach -->
<p>@ViewData["selected"]</p>
<section id="sellthrueffectivedsp">
    @if (((string)ViewData["selected"] == "territory") || ((string)ViewData["selected"] == "region"))
    {
        <div class="col-lg-6 col-sm-12">
            <h2 style="text-align:center">Sell Thru</h2>
            <!-- GRAPHIC -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Sell Thru Graphic</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>

                <div class="box-body row">
                    <div class="col-lg-12">
                        <div class="col-lg-3 col-sm-12 col-xs-12">
                            <strong>name</strong>
                        </div>
                        <div class="col-lg-9 col-sm-12 col-xs-12">
                            <div class="progress">
                                <div class="progress-bar progress-bar" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width:23%">
                                    23%
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>

            <div class="col-lg-6 col-sm-12">
                <h2 style="text-align:center">Sell Thru per Sales</h2>
                <!-- GRAPHIC -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Sell Thru per Sales Graphic</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    <div class="box-body row">
                        <div class="col-lg-12">
                            <div class="col-lg-3 col-sm-12 col-xs-12">
                                <strong style="color: green;">namee</strong>
                            </div>
                            <div class="col-lg-9 col-sm-12 col-xs-12">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="21" aria-valuemin="0" aria-valuemax="100" style="width:12%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
    }
    else
    {
        <div class="col-lg-12 col-sm-12">
            <h2 style="text-align:center">Sell Thru </h2>
            <!-- GRAPHIC -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Sell Thru Graphic</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body row">
                    <div class="col-lg-12">
                        <div class="col-lg-3 col-sm-12 col-xs-12">
                            <strong style="color:red"></strong>
                        </div>
                        <div class="col-lg-9 col-sm-12 col-xs-12">
                            <div class="progress">
                                <div class="progress-bar progress-bar-" role="progressbar" aria-valuenow="{{$sellthru[$i]["act"]}}" aria-valuemin="0" aria-valuemax="{{$maxSellThru}}" style="width:{{$sellthru[$i]["percentage"]/($maxSellThru/100)}}%">
                                    %
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    }

</section>